// Additional lessons — appended to LESSONS defined in data.js
LESSONS.push(
  {
    id: 'family',
    title: 'Family & Relationships',
    subtitle: 'Talk about your family and loved ones',
    icon: '👨‍👩‍👧',
    vocabulary: [
      { french: 'la famille', english: 'the family', pronunciation: 'lah fah-MEE-yuh' },
      { french: 'la mère', english: 'the mother', pronunciation: 'lah mair' },
      { french: 'le père', english: 'the father', pronunciation: 'luh pair' },
      { french: 'le frère', english: 'the brother', pronunciation: 'luh frair' },
      { french: 'la sœur', english: 'the sister', pronunciation: 'lah sur' },
      { french: 'les grands-parents', english: 'the grandparents', pronunciation: 'lay grahn-pah-RAHN' },
      { french: 'le mari / la femme', english: 'the husband / the wife', pronunciation: 'luh mah-REE / lah fam' },
      { french: 'les enfants', english: 'the children', pronunciation: 'lay zahn-FAHN' },
      { french: 'le fils / la fille', english: 'the son / the daughter', pronunciation: 'luh fees / lah fee' },
      { french: 'célibataire / marié(e)', english: 'single / married', pronunciation: 'say-lee-bah-TAIR / mah-ree-AY' },
    ],
    dialogue: [
      { speaker: 'Anna', french: 'Tu as des frères et sœurs ?', english: 'Do you have brothers and sisters?' },
      { speaker: 'Paul', french: 'Oui, j\'ai un frère et deux sœurs. Et toi ?', english: 'Yes, I have one brother and two sisters. And you?' },
      { speaker: 'Anna', french: 'Je suis fille unique. Mais j\'ai beaucoup de cousins !', english: 'I\'m an only child. But I have lots of cousins!' },
      { speaker: 'Paul', french: 'Tu es mariée ?', english: 'Are you married?' },
      { speaker: 'Anna', french: 'Non, je suis célibataire. Mon frère est marié — il a deux enfants.', english: 'No, I\'m single. My brother is married — he has two children.' },
      { speaker: 'Paul', french: 'Quelle belle famille !', english: 'What a lovely family!' },
    ],
    grammar: {
      title: 'Possessive Adjectives: mon, ma, mes',
      explanation: 'French possessive adjectives agree with the <strong>noun they describe</strong>, not the owner. Use <strong>mon</strong> (masculine), <strong>ma</strong> (feminine), <strong>mes</strong> (plural). Before a feminine noun starting with a vowel, use <strong>mon</strong> instead of <strong>ma</strong>.',
      examples: [
        { french: 'mon père / ma mère / mes parents', english: 'my father / my mother / my parents' },
        { french: 'ton frère / ta sœur', english: 'your brother / your sister (informal)' },
        { french: 'son mari / sa femme', english: 'his/her husband / his/her wife' },
      ],
    },
    quiz: [
      {
        question: 'How do you say "my sister" in French?',
        options: [
          { text: 'Ma sœur', correct: true },
          { text: 'Mon sœur', correct: false },
          { text: 'Mes sœur', correct: false },
          { text: 'Sa sœur', correct: false },
        ],
        explanation: '"Sœur" is feminine → use "ma." "Mon" is for masculine nouns. "Sa" means his/her sister.',
      },
      {
        question: 'What does "J\'ai deux enfants" mean?',
        options: [
          { text: 'I have two children.', correct: true },
          { text: 'I want two children.', correct: false },
          { text: 'I have two brothers.', correct: false },
          { text: 'She has two daughters.', correct: false },
        ],
        explanation: '"J\'ai" = I have. "Deux" = two. "Enfants" = children.',
      },
      {
        question: 'Which word means "the father"?',
        options: [
          { text: 'Le père', correct: true },
          { text: 'La mère', correct: false },
          { text: 'Le frère', correct: false },
          { text: 'Le fils', correct: false },
        ],
        explanation: '"Le père" = the father. "La mère" = the mother. "Le frère" = the brother. "Le fils" = the son.',
      },
      {
        question: 'Someone says "Je suis célibataire." What do they mean?',
        options: [
          { text: 'I am single.', correct: true },
          { text: 'I am married.', correct: false },
          { text: 'I am divorced.', correct: false },
          { text: 'I have no family.', correct: false },
        ],
        explanation: '"Célibataire" means single/unmarried. "Marié(e)" means married.',
      },
      {
        question: 'How do you ask "Do you have brothers and sisters?" in French?',
        options: [
          { text: 'Tu as des frères et sœurs ?', correct: true },
          { text: 'Tu es frère et sœur ?', correct: false },
          { text: 'Avez-vous la famille ?', correct: false },
          { text: 'Tu veux des enfants ?', correct: false },
        ],
        explanation: '"Tu as des frères et sœurs ?" uses "avoir" (to have) — the standard way to ask about siblings.',
      },
    ],
  },
  {
    id: 'food',
    title: 'Food & Eating Out',
    subtitle: 'Order a meal and discuss French food',
    icon: '🍽️',
    vocabulary: [
      { french: 'le déjeuner / le dîner', english: 'lunch / dinner', pronunciation: 'luh day-zhuh-NAY / luh dee-NAY' },
      { french: 'le pain', english: 'the bread', pronunciation: 'luh pan' },
      { french: 'le fromage', english: 'the cheese', pronunciation: 'luh froh-MAHZH' },
      { french: 'la viande', english: 'the meat', pronunciation: 'lah vyahnd' },
      { french: 'le poisson', english: 'the fish', pronunciation: 'luh pwah-SOHN' },
      { french: 'les légumes', english: 'the vegetables', pronunciation: 'lay lay-GEWM' },
      { french: 'Je suis végétarien(ne)', english: 'I am vegetarian', pronunciation: 'zhuh swee vay-zhay-tah-ree-AHN' },
      { french: 'Bon appétit !', english: 'Enjoy your meal!', pronunciation: 'bohn ah-pay-TEE' },
      { french: 'délicieux / délicieuse', english: 'delicious (m/f)', pronunciation: 'day-lee-SYUH / day-lee-SYUHZ' },
      { french: 'une table pour deux', english: 'a table for two', pronunciation: 'ewn tah-bluh poor duh' },
    ],
    dialogue: [
      { speaker: 'Serveur', french: 'Bonsoir ! Vous avez une réservation ?', english: 'Good evening! Do you have a reservation?' },
      { speaker: 'Client', french: 'Oui, une table pour deux, au nom de Dupont.', english: 'Yes, a table for two, under the name Dupont.' },
      { speaker: 'Serveur', french: 'Très bien. Voici le menu. Vous désirez ?', english: 'Very good. Here is the menu. What would you like?' },
      { speaker: 'Client', french: 'Je voudrais le poisson avec des légumes, s\'il vous plaît.', english: 'I\'d like the fish with vegetables, please.' },
      { speaker: 'Serveur', french: 'Excellent choix. Et comme boisson ?', english: 'Excellent choice. And to drink?' },
      { speaker: 'Client', french: 'Une carafe d\'eau, merci. C\'était délicieux !', english: 'A jug of water, thank you. It was delicious!' },
    ],
    grammar: {
      title: 'Partitive Articles: du, de la, des',
      explanation: 'When talking about an unspecified quantity, French uses <strong>partitive articles</strong>: <strong>du</strong> (masculine), <strong>de la</strong> (feminine), <strong>de l\'</strong> (before a vowel), <strong>des</strong> (plural). They translate as "some" — often omitted in English.',
      examples: [
        { french: 'Je mange du pain.', english: 'I eat (some) bread.' },
        { french: 'Tu veux de la viande ?', english: 'Do you want (some) meat?' },
        { french: 'Il commande des légumes.', english: 'He orders (some) vegetables.' },
      ],
    },
    quiz: [
      {
        question: 'Which French word means "cheese"?',
        options: [
          { text: 'Le fromage', correct: true },
          { text: 'Le poisson', correct: false },
          { text: 'La viande', correct: false },
          { text: 'Le pain', correct: false },
        ],
        explanation: '"Le fromage" = cheese. France is famous for its hundreds of cheese varieties!',
      },
      {
        question: 'How do you say "a table for two" in French?',
        options: [
          { text: 'Une table pour deux', correct: true },
          { text: 'Une table pour trois', correct: false },
          { text: 'Un menu pour deux', correct: false },
          { text: 'Deux tables, s\'il vous plaît', correct: false },
        ],
        explanation: '"Une table pour deux" is the standard phrase for requesting a table for two people.',
      },
      {
        question: 'Fill in the blank: "Je mange ___ pain." (I eat some bread.)',
        options: [
          { text: 'du', correct: true },
          { text: 'de la', correct: false },
          { text: 'des', correct: false },
          { text: 'un', correct: false },
        ],
        explanation: '"Pain" is masculine → use partitive "du." "De la" is for feminine nouns. "Un" would mean one specific loaf.',
      },
      {
        question: 'What does "Bon appétit !" mean?',
        options: [
          { text: 'Enjoy your meal!', correct: true },
          { text: 'Good morning!', correct: false },
          { text: 'The meal is ready!', correct: false },
          { text: 'Have a good day!', correct: false },
        ],
        explanation: '"Bon appétit" is said before eating — it wishes everyone a good appetite and enjoyment of the meal.',
      },
      {
        question: 'How do you say "I am vegetarian" in French?',
        options: [
          { text: 'Je suis végétarien(ne).', correct: true },
          { text: 'Je mange végétarien.', correct: false },
          { text: 'Je veux pas de viande.', correct: false },
          { text: 'Je suis sans viande.', correct: false },
        ],
        explanation: '"Je suis végétarien" (male) or "végétarienne" (female) is the correct phrase.',
      },
    ],
  },
  {
    id: 'health',
    title: 'Health & the Body',
    subtitle: 'Describe symptoms and visit a pharmacy',
    icon: '🏥',
    vocabulary: [
      { french: 'J\'ai mal à…', english: 'I have a pain in… / My … hurts', pronunciation: 'zhay mahl ah' },
      { french: 'la tête', english: 'the head', pronunciation: 'lah tet' },
      { french: 'le ventre', english: 'the stomach / belly', pronunciation: 'luh vahnt-ruh' },
      { french: 'la gorge', english: 'the throat', pronunciation: 'lah gorzh' },
      { french: 'le dos', english: 'the back', pronunciation: 'luh doh' },
      { french: 'la pharmacie', english: 'the pharmacy', pronunciation: 'lah far-mah-SEE' },
      { french: 'un médicament', english: 'a medicine / medication', pronunciation: 'uhn may-dee-kah-MAHN' },
      { french: 'une ordonnance', english: 'a prescription', pronunciation: 'ewn or-doh-NAHNS' },
      { french: 'Je ne me sens pas bien', english: 'I don\'t feel well', pronunciation: 'zhuh nuh muh sahn pah byahn' },
      { french: 'Appelez un médecin !', english: 'Call a doctor!', pronunciation: 'ah-play uhn mayd-SAN' },
    ],
    dialogue: [
      { speaker: 'Patient', french: 'Bonjour, je ne me sens pas bien.', english: 'Hello, I don\'t feel well.' },
      { speaker: 'Pharmacien', french: 'Qu\'est-ce que vous avez ?', english: 'What\'s wrong with you?' },
      { speaker: 'Patient', french: 'J\'ai mal à la gorge et j\'ai de la fièvre.', english: 'I have a sore throat and a fever.' },
      { speaker: 'Pharmacien', french: 'Depuis quand ?', english: 'Since when?' },
      { speaker: 'Patient', french: 'Depuis hier soir. C\'est grave ?', english: 'Since last night. Is it serious?' },
      { speaker: 'Pharmacien', french: 'Non, mais je vous recommande ce médicament. Prenez-le trois fois par jour.', english: 'No, but I recommend this medicine. Take it three times a day.' },
    ],
    grammar: {
      title: '"Avoir mal à" — Expressing Pain',
      explanation: 'To say something hurts, use <strong>avoir mal à + body part</strong>. The article contracts with "à": <strong>à + le = au</strong>, <strong>à + les = aux</strong>. "À la" and "à l\'" stay as-is.',
      examples: [
        { french: 'J\'ai mal à la tête.', english: 'I have a headache. (My head hurts.)' },
        { french: 'Il a mal au ventre.', english: 'He has a stomach ache.' },
        { french: 'Elle a mal aux pieds.', english: 'Her feet hurt.' },
      ],
    },
    quiz: [
      {
        question: 'How do you say "My head hurts" in French?',
        options: [
          { text: 'J\'ai mal à la tête.', correct: true },
          { text: 'Ma tête est mal.', correct: false },
          { text: 'Je suis mal à la tête.', correct: false },
          { text: 'J\'ai une tête mal.', correct: false },
        ],
        explanation: '"J\'ai mal à la tête" uses "avoir mal à" — the standard French construction for expressing pain.',
      },
      {
        question: 'Where do you go to buy medicine in France?',
        options: [
          { text: 'La pharmacie', correct: true },
          { text: 'La boulangerie', correct: false },
          { text: 'La gare', correct: false },
          { text: 'La mairie', correct: false },
        ],
        explanation: '"La pharmacie" is the pharmacy. Look for the green cross sign!',
      },
      {
        question: 'Someone says "Je ne me sens pas bien." What do they mean?',
        options: [
          { text: 'I don\'t feel well.', correct: true },
          { text: 'I feel very well.', correct: false },
          { text: 'I need a doctor.', correct: false },
          { text: 'I have a cold.', correct: false },
        ],
        explanation: '"Se sentir" = to feel. "Je ne me sens pas bien" = I don\'t feel well.',
      },
      {
        question: 'How do you say "He has a stomach ache"?',
        options: [
          { text: 'Il a mal au ventre.', correct: true },
          { text: 'Il a mal à le ventre.', correct: false },
          { text: 'Il a mal du ventre.', correct: false },
          { text: 'Il est mal au ventre.', correct: false },
        ],
        explanation: '"À + le" contracts to "au" — so "mal à le ventre" becomes "mal au ventre."',
      },
      {
        question: 'What is "une ordonnance"?',
        options: [
          { text: 'A prescription', correct: true },
          { text: 'A medicine', correct: false },
          { text: 'A doctor\'s appointment', correct: false },
          { text: 'A hospital', correct: false },
        ],
        explanation: '"Une ordonnance" is a prescription. You need one from a doctor ("un médecin") for certain medicines.',
      },
    ],
  },
  {
    id: 'weather',
    title: 'Weather & Seasons',
    subtitle: 'Talk about the weather and time of year',
    icon: '⛅',
    vocabulary: [
      { french: 'Quel temps fait-il ?', english: 'What\'s the weather like?', pronunciation: 'kel tahn fay-TEEL' },
      { french: 'Il fait beau', english: 'The weather is nice', pronunciation: 'eel fay BOH' },
      { french: 'Il fait mauvais', english: 'The weather is bad', pronunciation: 'eel fay moh-VAY' },
      { french: 'Il pleut', english: 'It\'s raining', pronunciation: 'eel PLUH' },
      { french: 'Il neige', english: 'It\'s snowing', pronunciation: 'eel NEZH' },
      { french: 'Il fait chaud / froid', english: 'It\'s hot / cold', pronunciation: 'eel fay shoh / frwah' },
      { french: 'le printemps / l\'été', english: 'spring / summer', pronunciation: 'luh pran-TAHN / lay-TAY' },
      { french: 'l\'automne / l\'hiver', english: 'autumn / winter', pronunciation: 'loh-TUN / lee-VAIR' },
      { french: 'nuageux / ensoleillé', english: 'cloudy / sunny', pronunciation: 'nwah-ZHUH / ahn-so-lay-YAY' },
      { french: 'un parapluie', english: 'an umbrella', pronunciation: 'uhn pah-rah-PLOO-ee' },
    ],
    dialogue: [
      { speaker: 'Claire', french: 'Quel temps fait-il à Paris en ce moment ?', english: 'What\'s the weather like in Paris right now?' },
      { speaker: 'Julien', french: 'Il fait froid et il pleut. C\'est typique pour novembre !', english: 'It\'s cold and raining. Typical for November!' },
      { speaker: 'Claire', french: 'Moi, je préfère l\'été. Il fait beau et chaud.', english: 'I prefer summer. The weather is nice and warm.' },
      { speaker: 'Julien', french: 'Moi aussi, mais j\'adore l\'hiver pour Noël.', english: 'Me too, but I love winter for Christmas.' },
      { speaker: 'Claire', french: 'Est-ce qu\'il neige à Paris en hiver ?', english: 'Does it snow in Paris in winter?' },
      { speaker: 'Julien', french: 'Rarement. Mais il fait très froid !', english: 'Rarely. But it gets very cold!' },
    ],
    grammar: {
      title: '"Il fait" and Weather Verbs',
      explanation: 'Most weather expressions use <strong>il fait + adjective</strong> for general conditions, or <strong>il + verb</strong> for specific phenomena. Never use "il est" for weather.',
      examples: [
        { french: 'Il fait beau aujourd\'hui.', english: 'The weather is nice today.' },
        { french: 'Il pleut souvent en automne.', english: 'It often rains in autumn.' },
        { french: 'Il fait très froid en hiver.', english: 'It\'s very cold in winter.' },
      ],
    },
    quiz: [
      {
        question: 'How do you ask "What\'s the weather like?" in French?',
        options: [
          { text: 'Quel temps fait-il ?', correct: true },
          { text: 'Quelle heure est-il ?', correct: false },
          { text: 'Quel est le temps ?', correct: false },
          { text: 'Comment fait-il ?', correct: false },
        ],
        explanation: '"Quel temps fait-il ?" is the standard weather question. Don\'t confuse with "Quelle heure est-il ?" (What time is it?).',
      },
      {
        question: 'What does "Il neige" mean?',
        options: [
          { text: 'It\'s snowing.', correct: true },
          { text: 'It\'s raining.', correct: false },
          { text: 'It\'s windy.', correct: false },
          { text: 'It\'s freezing.', correct: false },
        ],
        explanation: '"Il neige" = it\'s snowing, from "neiger" (to snow). "Il pleut" = it\'s raining.',
      },
      {
        question: 'Which sentence means "It\'s hot today"?',
        options: [
          { text: 'Il fait chaud aujourd\'hui.', correct: true },
          { text: 'Il fait froid aujourd\'hui.', correct: false },
          { text: 'Il fait beau aujourd\'hui.', correct: false },
          { text: 'Il fait mauvais aujourd\'hui.', correct: false },
        ],
        explanation: '"Chaud" = hot/warm. "Froid" = cold. "Beau" = nice/fine. "Mauvais" = bad.',
      },
      {
        question: 'What season is "l\'été"?',
        options: [
          { text: 'Summer', correct: true },
          { text: 'Winter', correct: false },
          { text: 'Spring', correct: false },
          { text: 'Autumn', correct: false },
        ],
        explanation: '"L\'été" = summer. "L\'hiver" = winter. "Le printemps" = spring. "L\'automne" = autumn.',
      },
      {
        question: 'You\'re going out in the rain. What do you need?',
        options: [
          { text: 'Un parapluie', correct: true },
          { text: 'Un manteau', correct: false },
          { text: 'Des lunettes de soleil', correct: false },
          { text: 'Un chapeau', correct: false },
        ],
        explanation: '"Un parapluie" = an umbrella. "Un manteau" = a coat. "Des lunettes de soleil" = sunglasses.',
      },
    ],
  }
);
