const LESSONS = [
  {
    id: 'greetings',
    title: 'Greetings & Introductions',
    subtitle: 'How to meet, greet, and say goodbye',
    icon: '👋',
    vocabulary: [
      { french: 'Bonjour', english: 'Hello / Good morning', pronunciation: 'bohn-ZHOOR' },
      { french: 'Bonsoir', english: 'Good evening', pronunciation: 'bohn-SWAHR' },
      { french: 'Au revoir', english: 'Goodbye', pronunciation: 'oh ruh-VWAHR' },
      { french: 'Salut', english: 'Hi / Bye (informal)', pronunciation: 'sah-LU' },
      { french: 'Je m\'appelle…', english: 'My name is…', pronunciation: 'zhuh mah-PELL' },
      { french: 'Enchanté(e)', english: 'Nice to meet you', pronunciation: 'ahn-shahn-TAY' },
      { french: 'Merci', english: 'Thank you', pronunciation: 'mair-SEE' },
      { french: 'De rien', english: 'You\'re welcome', pronunciation: 'duh ree-AHN' },
      { french: 'S\'il vous plaît', english: 'Please (formal)', pronunciation: 'seel voo PLAY' },
      { french: 'Comment vous appelez-vous ?', english: 'What is your name? (formal)', pronunciation: 'koh-mahn voo zah-play-VOO' },
    ],
    dialogue: [
      { speaker: 'Marie', french: 'Bonjour ! Je m\'appelle Marie.', english: 'Hello! My name is Marie.' },
      { speaker: 'Thomas', french: 'Bonjour, Marie. Je m\'appelle Thomas. Enchanté !', english: 'Hello, Marie. My name is Thomas. Nice to meet you!' },
      { speaker: 'Marie', french: 'Enchantée ! Vous êtes français ?', english: 'Nice to meet you too! Are you French?' },
      { speaker: 'Thomas', french: 'Oui, je suis français. Et vous ?', english: 'Yes, I\'m French. And you?' },
      { speaker: 'Marie', french: 'Non, je suis américaine. Au revoir, Thomas !', english: 'No, I\'m American. Goodbye, Thomas!' },
      { speaker: 'Thomas', french: 'Au revoir, Marie ! À bientôt !', english: 'Goodbye, Marie! See you soon!' },
    ],
    grammar: {
      title: 'Subject Pronouns: je, tu, vous',
      explanation: 'French has two ways to say "you": <strong>tu</strong> (informal, for friends and family) and <strong>vous</strong> (formal, for strangers, elders, or groups). When meeting someone new, always use <strong>vous</strong> to be polite.',
      examples: [
        { french: 'Tu t\'appelles comment ?', english: 'What\'s your name? (to a friend)' },
        { french: 'Vous vous appelez comment ?', english: 'What\'s your name? (formal)' },
        { french: 'Je m\'appelle Sophie.', english: 'My name is Sophie.' },
      ],
    },
    quiz: [
      {
        question: 'You arrive at a French café at 7pm. How do you greet the waiter?',
        options: [
          { text: 'Bonsoir', correct: true },
          { text: 'Bonjour', correct: false },
          { text: 'Au revoir', correct: false },
          { text: 'Salut', correct: false },
        ],
        explanation: '"Bonsoir" is used in the evening. "Bonjour" is for the morning and afternoon. "Salut" is too informal for a stranger.',
      },
      {
        question: 'Someone introduces themselves to you. What do you say to mean "Nice to meet you"?',
        options: [
          { text: 'Enchanté(e)', correct: true },
          { text: 'Au revoir', correct: false },
          { text: 'De rien', correct: false },
          { text: 'S\'il vous plaît', correct: false },
        ],
        explanation: '"Enchanté" (m) or "Enchantée" (f) means "delighted / nice to meet you." It\'s the standard response when being introduced.',
      },
      {
        question: 'A shopkeeper says "Merci !" after you hold the door. What do you reply?',
        options: [
          { text: 'De rien', correct: true },
          { text: 'Merci', correct: false },
          { text: 'Bonjour', correct: false },
          { text: 'Enchanté', correct: false },
        ],
        explanation: '"De rien" means "you\'re welcome" — the natural reply to "merci."',
      },
      {
        question: 'How do you tell someone your name in French?',
        options: [
          { text: 'Je m\'appelle…', correct: true },
          { text: 'Je suis appelle…', correct: false },
          { text: 'Mon nom est…', correct: false },
          { text: 'J\'ai nom…', correct: false },
        ],
        explanation: '"Je m\'appelle…" literally means "I call myself…" and is the standard phrase to introduce your name.',
      },
      {
        question: 'You\'re leaving your French host\'s home after dinner. What do you say?',
        options: [
          { text: 'Au revoir !', correct: true },
          { text: 'Bonjour !', correct: false },
          { text: 'S\'il vous plaît !', correct: false },
          { text: 'Enchanté !', correct: false },
        ],
        explanation: '"Au revoir" means "goodbye." "Bonjour" is a greeting, not a farewell.',
      },
    ],
  },
  {
    id: 'numbers-time',
    title: 'Numbers & Telling Time',
    subtitle: 'Count to 20 and ask what time it is',
    icon: '🕐',
    vocabulary: [
      { french: 'un, deux, trois', english: 'one, two, three', pronunciation: 'uhn, duh, twah' },
      { french: 'quatre, cinq, six', english: 'four, five, six', pronunciation: 'KAT-ruh, sank, sees' },
      { french: 'sept, huit, neuf', english: 'seven, eight, nine', pronunciation: 'set, weet, nuhf' },
      { french: 'dix, onze, douze', english: 'ten, eleven, twelve', pronunciation: 'dees, ohnz, dooz' },
      { french: 'quinze, vingt', english: 'fifteen, twenty', pronunciation: 'kanz, van' },
      { french: 'Quelle heure est-il ?', english: 'What time is it?', pronunciation: 'kel ur ay-TEEL' },
      { french: 'Il est… heures', english: 'It is… o\'clock', pronunciation: 'eel ay… ur' },
      { french: 'le matin', english: 'the morning', pronunciation: 'luh mah-TAN' },
      { french: 'l\'après-midi', english: 'the afternoon', pronunciation: 'lah-pray mee-DEE' },
      { french: 'le soir', english: 'the evening', pronunciation: 'luh SWAHR' },
    ],
    dialogue: [
      { speaker: 'Lucie', french: 'Excusez-moi, quelle heure est-il ?', english: 'Excuse me, what time is it?' },
      { speaker: 'Marc', french: 'Il est trois heures et demie.', english: 'It\'s half past three.' },
      { speaker: 'Lucie', french: 'Merci ! Le train part à quelle heure ?', english: 'Thank you! What time does the train leave?' },
      { speaker: 'Marc', french: 'À quatre heures vingt, je crois.', english: 'At four twenty, I think.' },
      { speaker: 'Lucie', french: 'Parfait, j\'ai le temps. Merci beaucoup !', english: 'Perfect, I have time. Thank you very much!' },
    ],
    grammar: {
      title: 'Telling Time with "Il est"',
      explanation: 'To tell the time in French, use <strong>Il est + [number] + heure(s)</strong>. Note: "heure" becomes "heures" for all times except 1 o\'clock. For half past, add <strong>et demie</strong>. For quarter past, add <strong>et quart</strong>.',
      examples: [
        { french: 'Il est une heure.', english: 'It is one o\'clock.' },
        { french: 'Il est deux heures et demie.', english: 'It is half past two.' },
        { french: 'Il est neuf heures et quart.', english: 'It is quarter past nine.' },
      ],
    },
    quiz: [
      {
        question: 'What is the French word for the number 15?',
        options: [
          { text: 'Quinze', correct: true },
          { text: 'Cinq', correct: false },
          { text: 'Douze', correct: false },
          { text: 'Vingt', correct: false },
        ],
        explanation: '"Quinze" = 15. "Cinq" = 5, "Douze" = 12, "Vingt" = 20.',
      },
      {
        question: 'How do you ask "What time is it?" in French?',
        options: [
          { text: 'Quelle heure est-il ?', correct: true },
          { text: 'Quel temps fait-il ?', correct: false },
          { text: 'Combien coûte-il ?', correct: false },
          { text: 'Où est l\'heure ?', correct: false },
        ],
        explanation: '"Quelle heure est-il ?" = "What time is it?" Note: "Quel temps fait-il ?" means "What\'s the weather like?"',
      },
      {
        question: 'How do you say "It is 8 o\'clock"?',
        options: [
          { text: 'Il est huit heures.', correct: true },
          { text: 'Il est huit heure.', correct: false },
          { text: 'C\'est huit heures.', correct: false },
          { text: 'Il a huit heures.', correct: false },
        ],
        explanation: 'Use "Il est [number] heures." — "heures" is plural for all hours except one. "C\'est" and "Il a" are not used for time.',
      },
      {
        question: 'Someone says "Je travaille le matin." What does that mean?',
        options: [
          { text: 'I work in the morning.', correct: true },
          { text: 'I work in the evening.', correct: false },
          { text: 'I work in the afternoon.', correct: false },
          { text: 'I work at night.', correct: false },
        ],
        explanation: '"Le matin" = the morning. "Le soir" = the evening. "L\'après-midi" = the afternoon.',
      },
      {
        question: 'What does "Il est deux heures et demie" mean?',
        options: [
          { text: 'It is half past two.', correct: true },
          { text: 'It is two o\'clock.', correct: false },
          { text: 'It is quarter past two.', correct: false },
          { text: 'It is two fifteen.', correct: false },
        ],
        explanation: '"Et demie" means "and a half" → half past. "Et quart" would mean quarter past.',
      },
    ],
  },
  {
    id: 'cafe',
    title: 'At the Café',
    subtitle: 'Order drinks and food like a local',
    icon: '☕',
    vocabulary: [
      { french: 'Je voudrais…', english: 'I would like…', pronunciation: 'zhuh voo-DRAY' },
      { french: 'un café', english: 'a coffee (espresso)', pronunciation: 'uhn kah-FAY' },
      { french: 'un thé', english: 'a tea', pronunciation: 'uhn tay' },
      { french: 'une eau', english: 'a water', pronunciation: 'ewn oh' },
      { french: 'un croissant', english: 'a croissant', pronunciation: 'uhn kwah-SAHN' },
      { french: 'l\'addition', english: 'the bill / check', pronunciation: 'lah-dee-SYOHN' },
      { french: 'C\'est combien ?', english: 'How much is it?', pronunciation: 'say kohm-BYAHN' },
      { french: 'Avez-vous… ?', english: 'Do you have… ?', pronunciation: 'ah-vay-VOO' },
      { french: 'Voilà', english: 'Here you are / There it is', pronunciation: 'vwah-LAH' },
      { french: 'Bonne journée', english: 'Have a good day', pronunciation: 'bon zhoor-NAY' },
    ],
    dialogue: [
      { speaker: 'Serveur', french: 'Bonjour ! Qu\'est-ce que vous désirez ?', english: 'Hello! What would you like?' },
      { speaker: 'Client', french: 'Je voudrais un café et un croissant, s\'il vous plaît.', english: 'I would like a coffee and a croissant, please.' },
      { speaker: 'Serveur', french: 'Très bien. Vous désirez autre chose ?', english: 'Very good. Would you like anything else?' },
      { speaker: 'Client', french: 'Non merci, c\'est tout. C\'est combien ?', english: 'No thank you, that\'s all. How much is it?' },
      { speaker: 'Serveur', french: 'Quatre euros cinquante, s\'il vous plaît.', english: 'Four euros fifty, please.' },
      { speaker: 'Client', french: 'Voilà. Merci, bonne journée !', english: 'Here you are. Thank you, have a good day!' },
    ],
    grammar: {
      title: '"Je voudrais" — Polite Ordering',
      explanation: '<strong>Je voudrais</strong> (I would like) is the polite, conditional form of "vouloir" (to want). Always use it when ordering — saying "Je veux" (I want) can sound rude. Follow it with a noun or infinitive.',
      examples: [
        { french: 'Je voudrais un café.', english: 'I would like a coffee.' },
        { french: 'Je voudrais l\'addition, s\'il vous plaît.', english: 'I would like the bill, please.' },
        { french: 'Je voudrais réserver une table.', english: 'I would like to reserve a table.' },
      ],
    },
    quiz: [
      {
        question: 'You want to order politely at a café. Which phrase do you use?',
        options: [
          { text: 'Je voudrais un thé.', correct: true },
          { text: 'Je veux un thé.', correct: false },
          { text: 'Donnez-moi un thé.', correct: false },
          { text: 'J\'ai besoin d\'un thé.', correct: false },
        ],
        explanation: '"Je voudrais" is the polite conditional form. "Je veux" (I want) is grammatically correct but can sound blunt or rude in a café.',
      },
      {
        question: 'How do you ask for the bill in a French restaurant?',
        options: [
          { text: 'L\'addition, s\'il vous plaît.', correct: true },
          { text: 'Le menu, s\'il vous plaît.', correct: false },
          { text: 'La carte, s\'il vous plaît.', correct: false },
          { text: 'Le prix, s\'il vous plaît.', correct: false },
        ],
        explanation: '"L\'addition" is the bill/check. "Le menu" is a set menu, "la carte" is the à la carte menu, "le prix" is the price.',
      },
      {
        question: 'What does "C\'est combien ?" mean?',
        options: [
          { text: 'How much is it?', correct: true },
          { text: 'What is it?', correct: false },
          { text: 'Where is it?', correct: false },
          { text: 'When is it?', correct: false },
        ],
        explanation: '"Combien" means "how much/many." "C\'est combien ?" is the everyday way to ask the price.',
      },
      {
        question: 'The waiter hands you your coffee and says "Voilà !" What does he mean?',
        options: [
          { text: 'Here you are!', correct: true },
          { text: 'Goodbye!', correct: false },
          { text: 'Enjoy your meal!', correct: false },
          { text: 'Thank you!', correct: false },
        ],
        explanation: '"Voilà" is used to present something — "here you are," "there it is," or "there you go."',
      },
      {
        question: 'You want to ask if the café has orange juice. How do you say it?',
        options: [
          { text: 'Avez-vous du jus d\'orange ?', correct: true },
          { text: 'Voulez-vous du jus d\'orange ?', correct: false },
          { text: 'Est-ce que vous mangez du jus d\'orange ?', correct: false },
          { text: 'Où est le jus d\'orange ?', correct: false },
        ],
        explanation: '"Avez-vous… ?" means "Do you have… ?" — the polite way to ask about availability. "Voulez-vous" means "Do you want."',
      },
    ],
  },
  {
    id: 'directions',
    title: 'Getting Around',
    subtitle: 'Ask for and understand directions',
    icon: '🗺️',
    vocabulary: [
      { french: 'Où est… ?', english: 'Where is… ?', pronunciation: 'oo ay' },
      { french: 'Tournez à gauche', english: 'Turn left', pronunciation: 'toor-NAY ah gohsh' },
      { french: 'Tournez à droite', english: 'Turn right', pronunciation: 'toor-NAY ah drwaht' },
      { french: 'Allez tout droit', english: 'Go straight ahead', pronunciation: 'ah-lay too drwah' },
      { french: 'la gare', english: 'the train station', pronunciation: 'lah gahr' },
      { french: 'l\'aéroport', english: 'the airport', pronunciation: 'lay-roh-POR' },
      { french: 'près d\'ici', english: 'near here', pronunciation: 'pray dee-SEE' },
      { french: 'loin d\'ici', english: 'far from here', pronunciation: 'lwan dee-SEE' },
      { french: 'à gauche', english: 'on the left', pronunciation: 'ah gohsh' },
      { french: 'au coin', english: 'on the corner', pronunciation: 'oh kwan' },
    ],
    dialogue: [
      { speaker: 'Touriste', french: 'Excusez-moi, où est la gare, s\'il vous plaît ?', english: 'Excuse me, where is the train station, please?' },
      { speaker: 'Passant', french: 'La gare ? Ce n\'est pas loin. Allez tout droit.', english: 'The station? It\'s not far. Go straight ahead.' },
      { speaker: 'Touriste', french: 'Tout droit, d\'accord. Ensuite ?', english: 'Straight ahead, okay. Then?' },
      { speaker: 'Passant', french: 'Tournez à gauche au coin de la rue. La gare est là, sur votre droite.', english: 'Turn left at the corner of the street. The station is there, on your right.' },
      { speaker: 'Touriste', french: 'C\'est loin à pied ?', english: 'Is it far on foot?' },
      { speaker: 'Passant', french: 'Non, environ cinq minutes. Bonne chance !', english: 'No, about five minutes. Good luck!' },
    ],
    grammar: {
      title: 'The Imperative for Directions',
      explanation: 'When giving directions in French, use the <strong>imperative (command) form</strong> of the verb. For formal situations, this is the same as the <em>vous</em> present tense form (without "vous"). For -ER verbs, drop the final -s.',
      examples: [
        { french: 'Allez tout droit.', english: 'Go straight ahead.' },
        { french: 'Tournez à droite.', english: 'Turn right.' },
        { french: 'Prenez la première rue à gauche.', english: 'Take the first street on the left.' },
      ],
    },
    quiz: [
      {
        question: 'How do you ask "Where is the airport?" in French?',
        options: [
          { text: 'Où est l\'aéroport ?', correct: true },
          { text: 'Qu\'est-ce que l\'aéroport ?', correct: false },
          { text: 'Comment est l\'aéroport ?', correct: false },
          { text: 'Quand est l\'aéroport ?', correct: false },
        ],
        explanation: '"Où est… ?" means "Where is… ?" — the essential phrase for asking directions.',
      },
      {
        question: 'A local tells you "Tournez à gauche." What should you do?',
        options: [
          { text: 'Turn left', correct: true },
          { text: 'Turn right', correct: false },
          { text: 'Go straight', correct: false },
          { text: 'Stop', correct: false },
        ],
        explanation: '"Gauche" = left. "Droite" = right. A useful trick: "gauche" sounds like "gauche" in English (awkward/left).',
      },
      {
        question: 'Someone says "Ce n\'est pas loin d\'ici." What does that mean?',
        options: [
          { text: 'It\'s not far from here.', correct: true },
          { text: 'It\'s very far from here.', correct: false },
          { text: 'It\'s near the station.', correct: false },
          { text: 'It\'s on the right.', correct: false },
        ],
        explanation: '"Loin" = far, "près" = near. "Ce n\'est pas loin" = "It\'s not far."',
      },
      {
        question: 'Which phrase means "Go straight ahead"?',
        options: [
          { text: 'Allez tout droit', correct: true },
          { text: 'Tournez à droite', correct: false },
          { text: 'Revenez en arrière', correct: false },
          { text: 'Prenez le bus', correct: false },
        ],
        explanation: '"Tout droit" literally means "all straight" — always straight ahead.',
      },
      {
        question: 'You want to get to the train station. How do you ask?',
        options: [
          { text: 'Où est la gare, s\'il vous plaît ?', correct: true },
          { text: 'Où est l\'aéroport, s\'il vous plaît ?', correct: false },
          { text: 'Où est l\'hôtel, s\'il vous plaît ?', correct: false },
          { text: 'Où est la banque, s\'il vous plaît ?', correct: false },
        ],
        explanation: '"La gare" is the train station. "L\'aéroport" = airport, "l\'hôtel" = hotel, "la banque" = bank.',
      },
    ],
  },
  {
    id: 'daily-routine',
    title: 'My Daily Routine',
    subtitle: 'Describe your day and use -ER verbs',
    icon: '📅',
    vocabulary: [
      { french: 'se lever', english: 'to get up', pronunciation: 'suh luh-VAY' },
      { french: 'manger', english: 'to eat', pronunciation: 'mahn-ZHAY' },
      { french: 'travailler', english: 'to work', pronunciation: 'trah-vah-YAY' },
      { french: 'dormir', english: 'to sleep', pronunciation: 'dor-MEER' },
      { french: 'aller', english: 'to go', pronunciation: 'ah-LAY' },
      { french: 'lundi, mardi', english: 'Monday, Tuesday', pronunciation: 'luhn-DEE, mar-DEE' },
      { french: 'mercredi, jeudi', english: 'Wednesday, Thursday', pronunciation: 'mair-kruh-DEE, zhuh-DEE' },
      { french: 'vendredi', english: 'Friday', pronunciation: 'vahn-druh-DEE' },
      { french: 'le week-end', english: 'the weekend', pronunciation: 'luh wee-KEHND' },
      { french: 'd\'habitude', english: 'usually / normally', pronunciation: 'dah-bee-TEWD' },
    ],
    dialogue: [
      { speaker: 'Sophie', french: 'Tu fais quoi le matin, d\'habitude ?', english: 'What do you usually do in the morning?' },
      { speaker: 'Lucas', french: 'Je me lève à sept heures. Je mange un croissant et je vais au travail.', english: 'I get up at 7. I eat a croissant and go to work.' },
      { speaker: 'Sophie', french: 'Tu travailles tous les jours ?', english: 'Do you work every day?' },
      { speaker: 'Lucas', french: 'Du lundi au vendredi. Le week-end, je dors jusqu\'à dix heures !', english: 'Monday to Friday. On weekends, I sleep until ten!' },
      { speaker: 'Sophie', french: 'Moi aussi ! J\'adore le week-end.', english: 'Me too! I love the weekend.' },
    ],
    grammar: {
      title: '-ER Verb Conjugation (Present Tense)',
      explanation: 'Most French verbs end in <strong>-ER</strong>. To conjugate them, remove the -ER and add the correct ending. For <em>parler</em> (to speak): <strong>je parl-e, tu parl-es, il/elle parl-e, nous parl-ons, vous parl-ez, ils parl-ent</strong>. The endings -e, -es, -e, and -ent are all silent — only -ons and -ez are pronounced differently.',
      examples: [
        { french: 'Je mange une pomme.', english: 'I eat an apple.' },
        { french: 'Elle travaille le lundi.', english: 'She works on Mondays.' },
        { french: 'Nous parlons français.', english: 'We speak French.' },
      ],
    },
    quiz: [
      {
        question: 'Which day comes after "mardi" (Tuesday)?',
        options: [
          { text: 'Mercredi', correct: true },
          { text: 'Lundi', correct: false },
          { text: 'Jeudi', correct: false },
          { text: 'Vendredi', correct: false },
        ],
        explanation: 'The French week: lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche.',
      },
      {
        question: 'How do you say "I work" in French?',
        options: [
          { text: 'Je travaille', correct: true },
          { text: 'Je travailler', correct: false },
          { text: 'Je travailles', correct: false },
          { text: 'Je travaillons', correct: false },
        ],
        explanation: 'For -ER verbs with "je," add -e: travaill-e → je travaille. The -e is silent.',
      },
      {
        question: 'What does "D\'habitude, je me lève à huit heures" mean?',
        options: [
          { text: 'Usually, I get up at eight o\'clock.', correct: true },
          { text: 'Sometimes, I go to bed at eight.', correct: false },
          { text: 'Usually, I sleep until eight.', correct: false },
          { text: 'Every day, I wake up late.', correct: false },
        ],
        explanation: '"D\'habitude" = usually. "Se lever" = to get up. "À huit heures" = at eight o\'clock.',
      },
      {
        question: 'Which sentence is correctly conjugated?',
        options: [
          { text: 'Elle mange une salade.', correct: true },
          { text: 'Elle manges une salade.', correct: false },
          { text: 'Elle mangent une salade.', correct: false },
          { text: 'Elle mangez une salade.', correct: false },
        ],
        explanation: 'For il/elle with -ER verbs, the ending is -e (silent): manger → elle mange.',
      },
      {
        question: 'How do you say "on the weekend" in French?',
        options: [
          { text: 'Le week-end', correct: true },
          { text: 'La semaine', correct: false },
          { text: 'Les jours fériés', correct: false },
          { text: 'En vacances', correct: false },
        ],
        explanation: '"Le week-end" is used in French, borrowed directly from English. "La semaine" = the week, "les jours fériés" = public holidays.',
      },
    ],
  },
  {
    id: 'shopping',
    title: 'Shopping',
    subtitle: 'Ask prices, describe items, and negotiate',
    icon: '🛍️',
    vocabulary: [
      { french: 'Combien ça coûte ?', english: 'How much does it cost?', pronunciation: 'kohm-BYAHN sah KOOT' },
      { french: 'Je cherche…', english: 'I\'m looking for…', pronunciation: 'zhuh SHAIRSH' },
      { french: 'C\'est trop cher', english: 'It\'s too expensive', pronunciation: 'say troh SHAIR' },
      { french: 'la taille', english: 'the size', pronunciation: 'lah TIE' },
      { french: 'la couleur', english: 'the color', pronunciation: 'lah koo-LUR' },
      { french: 'rouge / bleu / noir', english: 'red / blue / black', pronunciation: 'roozh / bluh / nwahr' },
      { french: 'grand / petit', english: 'big / small', pronunciation: 'grahn / puh-TEE' },
      { french: 'Je peux essayer ?', english: 'Can I try it on?', pronunciation: 'zhuh puh eh-say-YAY' },
      { french: 'Je le prends', english: 'I\'ll take it', pronunciation: 'zhuh luh PRAHN' },
      { french: 'la caisse', english: 'the cash register / checkout', pronunciation: 'lah kess' },
    ],
    dialogue: [
      { speaker: 'Vendeur', french: 'Bonjour ! Je peux vous aider ?', english: 'Hello! Can I help you?' },
      { speaker: 'Client', french: 'Oui, je cherche un pull bleu, taille moyenne.', english: 'Yes, I\'m looking for a blue sweater, medium size.' },
      { speaker: 'Vendeur', french: 'Voilà un beau modèle. Combien ça coûte ?', english: 'Here\'s a nice one. How much does it cost?' },
      { speaker: 'Client', french: 'Soixante euros.', english: 'Sixty euros.' },
      { speaker: 'Client', french: 'C\'est un peu cher. Je peux essayer ?', english: 'That\'s a bit expensive. Can I try it on?' },
      { speaker: 'Vendeur', french: 'Bien sûr ! Les cabines sont là-bas.', english: 'Of course! The fitting rooms are over there.' },
    ],
    grammar: {
      title: 'Adjective Agreement',
      explanation: 'In French, adjectives must <strong>agree in gender and number</strong> with the noun they describe. Add <strong>-e</strong> for feminine, <strong>-s</strong> for plural, <strong>-es</strong> for feminine plural. Some adjectives change form entirely.',
      examples: [
        { french: 'un pull rouge / une veste rouge', english: 'a red sweater / a red jacket (rouge stays the same)' },
        { french: 'un grand sac / une grande valise', english: 'a big bag / a big suitcase (add -e for feminine)' },
        { french: 'un pull bleu / une robe bleue', english: 'a blue sweater / a blue dress (add -e for feminine)' },
      ],
    },
    quiz: [
      {
        question: 'You want to ask the price of a shirt. What do you say?',
        options: [
          { text: 'Combien ça coûte ?', correct: true },
          { text: 'Quelle est la couleur ?', correct: false },
          { text: 'Quelle est la taille ?', correct: false },
          { text: 'Où est la caisse ?', correct: false },
        ],
        explanation: '"Combien ça coûte ?" = "How much does it cost?" — the key shopping phrase.',
      },
      {
        question: 'You\'re looking for a red dress. How do you say "red dress" correctly?',
        options: [
          { text: 'Une robe rouge', correct: true },
          { text: 'Une rouge robe', correct: false },
          { text: 'Un robe rouge', correct: false },
          { text: 'Une robe rouges', correct: false },
        ],
        explanation: '"Robe" (dress) is feminine → "une robe." "Rouge" doesn\'t change form for feminine. Adjectives follow the noun in French.',
      },
      {
        question: 'What does "Je cherche une veste noire" mean?',
        options: [
          { text: 'I\'m looking for a black jacket.', correct: true },
          { text: 'I found a black jacket.', correct: false },
          { text: 'I\'d like a blue jacket.', correct: false },
          { text: 'Do you have a black jacket?', correct: false },
        ],
        explanation: '"Je cherche" = I\'m looking for. "Une veste" = a jacket. "Noire" = black (feminine form of "noir").',
      },
      {
        question: 'How do you ask if you can try something on?',
        options: [
          { text: 'Je peux essayer ?', correct: true },
          { text: 'Je voudrais payer.', correct: false },
          { text: 'Où est la taille ?', correct: false },
          { text: 'C\'est trop petit.', correct: false },
        ],
        explanation: '"Je peux essayer ?" = "Can I try it on?" "Essayer" means to try/try on. "Voudrais payer" = would like to pay.',
      },
      {
        question: 'The item costs €150. You think it\'s too expensive. What do you say?',
        options: [
          { text: 'C\'est trop cher.', correct: true },
          { text: 'C\'est parfait.', correct: false },
          { text: 'Je le prends.', correct: false },
          { text: 'C\'est gratuit ?', correct: false },
        ],
        explanation: '"C\'est trop cher" = "It\'s too expensive." "C\'est parfait" = "It\'s perfect." "Je le prends" = "I\'ll take it." "C\'est gratuit ?" = "Is it free?"',
      },
    ],
  },
];
